#! /usr/bin/env ruby

Command "My-RunShellScript-2" do
  account_ids []
  content do
    __dsl do
      schemaVersion "2.0"
      description "my4 Run a shell script or specify the path to a script to run."
      parameters do
        commands do
          type "StringList"
          description "(Required) Specify the commands to run or the paths to existing scripts on the instance."
          minItems 1
          displayType "textarea"
        end
        workingDirectory do
          type "String"
          default ""
          description "(Optional) The path to the working directory on your instance."
          maxChars 4096
        end
        executionTimeout do
          type "String"
          default "3600"
          description "(Optional) The time in seconds for a command to be completed before it is considered to have failed. Default is 3600 (1 hour). Maximum is 28800 (8 hours)."
          allowedPattern "([1-9][0-9]{0,3})|(1[0-9]{1,4})|(2[0-7][0-9]{1,3})|(28[0-7][0-9]{1,2})|(28800)"
        end
      end
      mainSteps do |*|
        action "aws:runShellScript"
        name "runShellScript"
        inputs do
          commands "{{ commands }}"
        end
      end
    end
  end

end
